map:
  indicator: ["indicator", "value", "ioc"]
  indicator_type: ["type", "indicator_type"]
  first_seen: ["first_seen", "timestamp"]
  last_seen: ["last_seen", "timestamp"]
  confidence: ["confidence"]
  references: ["refs", "references"]
  desc: ["description", "title"]

coerce:
  indicator_type: "auto"

defaults:
  confidence: "medium"

pass_through: []
